name: Build and Publish
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  publish_linux:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment:
      name: pypi
      url: https://pypi.org/p/boilerplater
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools setuptools-scm wheel
          pip install --upgrade -e .'[development]'
      - name: Build the distribution package
        run: |
          python -m build --wheel --outdir ./dist
          python -m build --sdist --outdir ./dist
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@release/v1
