name: test.yml
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main
permissions:
  contents: read
jobs:
  test_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools setuptools-scm wheel
          pip install --upgrade -e .'[development]'
      - name: Format and lint
        run: |
          isort . --check --diff
          ruff format --check --exit-non-zero-on-fix .
          ruff check --exit-non-zero-on-fix .
      - name: Run tests with pytest
        run: pytest .
